"""empty message

Revision ID: 915720a0eaab
Revises: 22509fe130c5
Create Date: 2021-08-27 08:20:13.674878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915720a0eaab'
down_revision = '22509fe130c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_usuario', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tb_usuario', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tb_usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'tb_usuario', ['username'])
    op.create_unique_constraint(None, 'tb_usuario', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_usuario', type_='unique')
    op.drop_constraint(None, 'tb_usuario', type_='unique')
    op.alter_column('tb_usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tb_usuario', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tb_usuario', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
