"""empty message

Revision ID: 965e37219e86
Revises: c14a27b8ca16
Create Date: 2021-08-29 18:12:18.199722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965e37219e86'
down_revision = 'c14a27b8ca16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_permissao',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tb_vinculo_permissao_funcao',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_permissao', sa.BigInteger(), nullable=True),
    sa.Column('id_funcao', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_funcao'], ['tb_funcao.id'], ),
    sa.ForeignKeyConstraint(['id_permissao'], ['tb_permissao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_vinculo_usuario_funcao',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('id_funcao', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_funcao'], ['tb_funcao.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_vinculo_usuario_funcao')
    op.drop_table('tb_vinculo_permissao_funcao')
    op.drop_table('tb_permissao')
    # ### end Alembic commands ###
