"""empty message

Revision ID: 94b1e123165a
Revises: 965e37219e86
Create Date: 2021-09-23 17:00:12.611833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b1e123165a'
down_revision = '965e37219e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_funcao', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tb_permissao', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_permissao', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tb_funcao', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
